### ISSUE TITLE
Package fails to compile with clang (MacOS)

### ISSUE THREAD

**Issue by ahmohamed** [lifs-tools/rgoslin-old#1]
Thanks for an awesome tool.

The package currently fails to compile with MacOS' Clang, giving many errors related to undefined template usage. It looks like a missing `# include`. Here is the first error (I can send the full output if needed). 

```
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:642:
/Library/Developer/CommandLineTools/usr/include/c++/v1/utility:321:9: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    _T2 second;
```

**Comment by dominik-kopczynski** [comment]
Thank you very much for reporting the issue. We will check it and try to fix it as soon as possible. Can you please provide us the complete set of error messages? Thanks.

**Comment by ahmohamed** [comment]
Sure. Here they are https://pastebin.com/ssCwqfTF

It may help if you setup CI testing (travis, github actions). I can help if you want.

**Comment by nilshoffmann** [comment]
We do build the package with travis here: https://travis-ci.org/github/lifs-tools/rgoslin
Travis does support osx as a target, too, so I will update the CI to include that.

**Comment by dominik-kopczynski** [comment]
To reproduce the error on our system: can you tell us the version numbers of your macOS, clang, xcode, R? Thank you.

**Comment by ahmohamed** [comment]
R
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6
```

clang
```
> clang -v
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Xcode command line tools
```
> xcode-select -v
xcode-select version 2349.
```

**Comment by nilshoffmann** [comment]
@ahmohamed  Please check!
Latest version [builds on travis under OS X](https://travis-ci.org/github/lifs-tools/rgoslin/builds/678515719), manually tested on OS X Catalina with [latest R](https://cran.r-project.org/bin/macosx/R-3.6.3.pkg), XCode and with .Renviron removal of homebrew installed clang works. Currently preparing release 1.0.2. 

These guides here were helpful:

- https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/
- https://github.com/rmacoslib/r-macos-rtools/releases

**Comment by ahmohamed** [comment]
Thanks for the quick fix! Installed and tested. I didn't have to modify any setup on my system. Awesome!
