### ISSUE TITLE
Add examples for parsing fragments / adducts

### ISSUE THREAD

**Issue by ahmohamed** [lifs-tools/rgoslin-old#2]
It's me again :)

I couldn't find any example for parsing lipids with adduct information (`'PC 32:1 [M+H]'` for example). I tried parsing with and without specifying `GoslinFragments` as grammar, and both return `NOT_PARSABLE`.

**Comment by dominik-kopczynski** [comment]
Hi Ahmed, sorry for this. The correct notation is: "PC 32:1[M+H]1+". It is the IUPAC notation. Note that there is no space between the lipid name and the adduct. We will add some examples. Cheers

**Comment by nilshoffmann** [comment]
There was a slight bug in the R implementation where the normalized name would return the adduct as well. The next version will contain two additional columns "Adduct" and "AdductCharge", while the normalized name will not have the adduct anylonger.

**Comment by nilshoffmann** [comment]
@ahmohamed This should be fixed with the next 2.0.0 release that we are currently preparing https://github.com/lifs-tools/rgoslin/tree/v2.0
