### ISSUE TITLE
Cyclopropane fatty acids

### ISSUE THREAD

**Issue by michaelwitting** [lifs-tools/rgoslin-old#3]
Hi,

is there a support for cyclopropane fatty acids, e.g. `FA 19:0;[11-13cy3:0]`. This is according to the 2020 update paper on the nomenclature.

Best,

Michael

**Comment by dominik-kopczynski** [comment]
Hi Michael,

Thank you for the question. Currently, we are supporting only the old shorthand nomenclature, but we are working on supporting the new one. However, it will take some time (at least til end of April), since we discovered some potential pitfalls within the new nomenclature, which have to be discussed. I will keep you informed as soon as we'll support the new nomenclature.

Cheers,
Dominik

**Comment by michaelwitting** [comment]
Thanks Dominik!

**Comment by dominik-kopczynski** [comment]
Hi Michael,

we've finished the alpha version of goslin v2.0 capable of reading / writing the new shorthand nomenclature. However, at the moment it is only available in Python. The C++, R, Java implementations will of course follow soon. However, I am searching for beta testers running some tests and spotting possible issues. Would it be possible for you or someone from your team to run some of your lipid lists through pygoslin and proof read them? I would provide everything including an instruction how to run the python code.

Cheers

**Comment by michaelwitting** [comment]
Hi Dominik,

I can check with my little Python knowledge. I'm a bit busy at the moment, but I will try to squeeze it in. Please send me a reminder some time so it is not falling down the table.

Best regards,

Michael

**Comment by dominik-kopczynski** [comment]
Thank you very much, Michael. As soon as I've fixed all occurring bugs, I'll send you a reminder by end of this week. Cheers.

**Comment by dominik-kopczynski** [comment]
Hi Michael, we eventually updated now Goslin's C++/Python/R versions (including the latest shorthand nomenclature). They are located in their corresponding github repositories in the "v2.0" development branches but are already in the beta phase. Would you like to test one of the new versions. Thank you and Cheers

**Comment by michaelwitting** [comment]
Thx! I will give it a try in the next days.
