### ISSUE TITLE
Parsing Acylcarnitine

### ISSUE THREAD

**Issue by JauntyJJS** [lifs-tools/rgoslin-old#5]
Hi,

I am currently using rgoslin release version 1.1.2

I was trying to use it to parse some Acylcarnitine. 
Here are some in LIPIDMAPS

https://www.lipidmaps.org/data/structure/LMSDSearch.php?Mode=ProcessClassSearch&LMID=LMFA0707

Unfortunately, this is what I get.

```{r}
library("rgoslin")

isValidLipidName("CAR 12:0")
#> Warning in rcpp_is_valid_lipid_name(lipidName): Parsing of lipid name 'CAR 12:0'
#> caused an exception: Lipid not found
#> [1] FALSE
Created on 2021-08-12 by the reprex package (v2.0.1)
```

Will there be support for this lipid class in the future ?

Thank you.

**Comment by dominik-kopczynski** [comment]
Hi Jaunty,

Thank you for your question. Yes, we are very very close to release all new goslin implementations including rgoslin 2.0. In this version, the CAR lipid class is included and the sum formula / mass can be calculated on top. Currently, we are in the beta testing phase, but in (at most) two weeks, we will release all implementations.

Cheers,
Dominik

**Comment by JauntyJJS** [comment]
Noted with thanks.
